$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: multidim-features
version: 1
description: MultiDimensionalFeatures environment with PyTorch + SAE Lens
build:
  path: ..
  dockerfile_path: Dockerfile
